/**
 * Application constants
 */

export const TRANSACTION_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
};

export const TRANSACTION_TYPE = {
  SEND: 'SEND',
  RECEIVE: 'RECEIVE'
};

export const REQUEST_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED'
};

export const NOTIFICATION_TYPE = {
  TRANSACTION_SENT: 'TRANSACTION_SENT',
  TRANSACTION_RECEIVED: 'TRANSACTION_RECEIVED',
  REQUEST_RECEIVED: 'REQUEST_RECEIVED',
  REQUEST_ACCEPTED: 'REQUEST_ACCEPTED',
  REQUEST_REJECTED: 'REQUEST_REJECTED',
  REQUEST_CANCELLED: 'REQUEST_CANCELLED'
};

export const MAX_TRANSACTION_AMOUNT = 100000; // ₹1,00,000
export const MIN_TRANSACTION_AMOUNT = 1; // ₹1
export const REQUEST_EXPIRY_DAYS = 7; // Requests expire after 7 days
